'--- Idioma ---
'Autor: Guilherme Pereira Porto Londe
'Última modificação: 09 de março de 2018

Imports Microsoft.VisualBasic

Public Class Idioma
    Public Tabela(40, 2) As String

    Public Sub New()
        Tabela(0, 0) = New String("Novo (Ctrl + N)")
        Tabela(0, 1) = New String("New (Ctrl + N)")
        Tabela(1, 0) = New String("Abrir (Ctrl + O)")
        Tabela(1, 1) = New String("Open (Ctrl + O)")
        Tabela(2, 0) = New String("Salvar (Ctrl + S)")
        Tabela(2, 1) = New String("Save (Ctrl + S)")
        Tabela(3, 0) = New String("Salvar como...")
        Tabela(3, 1) = New String("Save as...")
        Tabela(4, 0) = New String("Desfazer (Ctrl + Z)")
        Tabela(4, 1) = New String("Undo (Ctrl + Z)")
        Tabela(5, 0) = New String("Refazer (Ctrl + Y)")
        Tabela(5, 1) = New String("Redo (Ctrl + Y)")
        Tabela(6, 0) = New String("Recortar (Ctrl + X)")
        Tabela(6, 1) = New String("Cut (Ctrl + X)")
        Tabela(7, 0) = New String("Copiar (Ctrl + C)")
        Tabela(7, 1) = New String("Copy (Ctrl + C)")
        Tabela(8, 0) = New String("Colar (Ctrl + V)")
        Tabela(8, 1) = New String("Paste (Ctrl + V)")
        Tabela(9, 0) = New String("Excluir (Del)")
        Tabela(9, 1) = New String("Delete (Del)")
        Tabela(10, 0) = New String("SelecionarTudo (Ctrl + A)")
        Tabela(10, 1) = New String("Select all (Ctrl + A)")
        Tabela(11, 0) = New String("Barra de menu")
        Tabela(11, 1) = New String("Menu bar")
        Tabela(12, 0) = New String("Grade")
        Tabela(12, 1) = New String("Grid")
        Tabela(13, 0) = New String("Ativação da nota")
        Tabela(13, 1) = New String("Note activation")
        Tabela(14, 0) = New String("Modo inserção (Ctrl + I)")
        Tabela(14, 1) = New String("Insertion mode (Ctrl + I)")
        Tabela(15, 0) = New String("Modo cascata (Ctrl + D)")
        Tabela(15, 1) = New String("Auto ripple (Ctrl + D)")
        Tabela(16, 0) = New String("Idioma")
        Tabela(16, 1) = New String("Idiom")
        Tabela(17, 0) = New String("Arquivo")
        Tabela(17, 1) = New String("File")
        Tabela(18, 0) = New String("Editar")
        Tabela(18, 1) = New String("Edit")
        Tabela(19, 0) = New String("Exibir")
        Tabela(19, 1) = New String("Show")
        Tabela(20, 0) = New String("Configurações")
        Tabela(20, 1) = New String("Settings")
        Tabela(21, 0) = New String("Anterior (Seta esquerda)")
        Tabela(21, 1) = New String("Previous (Left arrow)")
        Tabela(22, 0) = New String("Tocar (Espaço)")
        Tabela(22, 1) = New String("Play (Space)")
        Tabela(23, 0) = New String("Parar (Backspace)")
        Tabela(23, 1) = New String("Stop (Backspace)")
        Tabela(24, 0) = New String("Próximo (Seta direita)")
        Tabela(24, 1) = New String("Next (Right arrow)")
        Tabela(25, 0) = New String("Velocidade do player")
        Tabela(25, 1) = New String("Player's speed")
        Tabela(26, 0) = New String("Português")
        Tabela(26, 1) = New String("English")
        Tabela(27, 0) = New String("Volume")
        Tabela(27, 1) = New String("Volume")
        Tabela(28, 0) = New String("Compositor fácil de piano")
        Tabela(28, 1) = New String("Easy piano composer")
        Tabela(29, 0) = New String("Selecione uma melodia para abrir")
        Tabela(29, 1) = New String("Select a melody to open")
        Tabela(30, 0) = New String("Melodia")
        Tabela(30, 1) = New String("Melody")
        Tabela(31, 0) = New String("Salvar melodia como...")
        Tabela(31, 1) = New String("Save melody as...")
        Tabela(32, 0) = New String("Deseja salvar as alterações?")
        Tabela(32, 1) = New String("Do you want to save before exit?")
    End Sub

End Class
